##################################################################################
# A default configuration that will be loaded for all jupyter books
# Users are expected to override these values in their own `_config.yml` file.
# This is also the "master list" of all allowed keys and values.

##################################################################################
# Book settings. Learn more at https://jupyterbook.org/customize/config.html
title                       : tecGeomDGGE - Técnicas Geométricas de Desenho Geológico e Geologia Estrutural
author                      : Alex F. Antunes
copyright                   : "2023"
logo                        : logo.png
exclude_patterns            : [_build, Thumbs.db, .DS_Store, "**.ipynb_checkpoints"]
only_build_toc_files        : true

##################################################################################
# Execution settings. See https://jupyterbook.org/content/execute.html
# Force re-execution of notebooks on each build.
execute:
  execute_notebooks         : force
  allow_errors              : true

##################################################################################
# Parse and render settings
#parse:
#  myst_enable_extensions:  # default extensions to enable in the myst parser. See https://myst-parser.readthedocs.io/en/latest/using/syntax-optional.html
#    - amsmath

mystnb:
  remove-output             : true

#################################################################################
# LaTeX-specific settings
# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname              : tecGeomDGGE.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
    - conteudo/referencias.bib

##################################################################################
# Launch button settings
launch_buttons:
  notebook_interface        : jupyterlab              # The interface interactive links will activate ["classic", "jupyterlab"]
  binderhub_url             : "https://mybinder.org"  # The URL for your BinderHub (e.g., https://mybinder.org)
  thebe                     : true                    # to make code cells executable

# Information about where the book exists on the web
#repository:
  url                       : https://github.com/afantunes74/tecGeomDGGE  # Online location of your book
  #path_to_book              : docs      # Optional path to your book, relative to the repository root
  branch                    : gh=pages    # Which branch of the repository should be used when creating links (optional)

##################################################################################
# HTML-specific settings. # See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
# Add GitHub buttons to your book
#html:
#  use_issues_button         : true  # Whether to add an "open an issue" button
#  use_repository_button     : true  # Whether to add a link to your repository button

##################################################################################
# Advanced and power-user settings
sphinx:
  config:
    bibtex_reference_style  : author_year
    mathjax_path            : https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js